name = "cloudmix-ui-storybook"
main = "src/worker.ts"
compatibility_date = "2023-10-30"

workers_dev = false
routes = [{ pattern = "ui.cloudmix.dev", custom_domain = true }]

[site]
bucket = "./storybook-static"

[build]
command = "pnpm build"
